Testing s3 connection

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -231,10 +231,7 @@ jobs:
             unzip -v | head -n 1
 
             echo "=== Testing S3 Connection ==="
-            aws --region ap-south-1 s3 ls s3://chimein-test-bucket || echo "S3 connection failed"
-
-            echo "=== Testing CodeDeploy Connection ==="
-            aws --region ap-south-1 deploy list-applications || echo "CodeDeploy connection failed"
+            aws --region ap-south-1 s3 ls s3://chimein-bucket || echo "S3 connection failed"
       - *notify-on-fail
 
   terraform-plan-and-apply:
